name: "Auto Assign Action"

on:
  - pull_request_target

jobs:
  triage:
    name: "Auto Assign"
    permissions:
      contents: read
      pull-requests: write

    runs-on: ubuntu-latest

    steps:
      - uses: kentaro-m/auto-assign-action@v1.2.4
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
