name: "Code Review Workflow"

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - develop

jobs:
  code-review:
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout code"
        uses: actions/checkout@v3

      - name: "Run Node.js script"
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: "Fetch pull request information"
        id: pr-info
        uses: actions/github-script@v3
        with:
          github-token: ${{ secrets.GH_TOKEN }}
          script: |
            const pr = context.payload.pull_request;
            console.log(` Pull request information: ${JSON.stringify(pr)}`);
